name: Slack Alert
description: Send a Slack alert message

inputs:
  message:
    description: The message to send to Slack
    required: true
  mrkdwn:
    description: The markdown message to send to Slack
    required: false
  token:
    description: The Slack bot token to use for api calls
    required: true
  channel:
    description: The Slack channel to send the alert to
    required: true

runs:
  using: composite
  steps:
    - name: Build Slack payload
      id: build-payload
      shell: bash
      run: |
        # Build blocks array conditionally
        PR_URL="${{ github.event.pull_request.html_url }}"
        COMMIT_URL="${{ github.event.head_commit.url }}"

        # Start building the blocks array
        BLOCKS='[
          {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "${{ inputs.message }}"
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "${{ inputs.mrkdwn || inputs.message }}"
            }
          }'

        # Add PR/commit context block if URL exists
        if [[ -n "$PR_URL" || -n "$COMMIT_URL" ]]; then
          BLOCKS="$BLOCKS,
          {
            \"type\": \"context\",
            \"elements\": [
              {
                \"type\": \"mrkdwn\",
                \"text\": \"${PR_URL:-$COMMIT_URL}\"
              }
            ]
          }"
        fi

        # Add workflow run context block (always included)
        BLOCKS="$BLOCKS,
          {
            \"type\": \"context\",
            \"elements\": [
              {
                \"type\": \"mrkdwn\",
                \"text\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
              }
            ]
          }
        ]"

        # Build complete payload
        PAYLOAD=$(cat <<EOF
        {
          "channel": "${{ inputs.channel }}",
          "text": "${{ inputs.message }}",
          "blocks": $BLOCKS
        }
        EOF
        )

        # Output payload for next step
        echo "payload<<PAYLOAD_EOF" >> $GITHUB_OUTPUT
        echo "$PAYLOAD" >> $GITHUB_OUTPUT
        echo "PAYLOAD_EOF" >> $GITHUB_OUTPUT

    - name: Alert on Slack
      id: slack
      uses: slackapi/slack-github-action@v2.1.1
      with:
        errors: true
        method: chat.postMessage
        token: ${{ inputs.token }}
        payload: ${{ steps.build-payload.outputs.payload }}
