name: Setup pnpm
description: Setup pnpm

inputs:
  working-directory:
    description: The working directory of the project
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: 'pnpm'
    - run: npm install -g corepack@0.31.0
      shell: sh
    - run: corepack enable
      shell: sh
    - run: pnpm install --frozen-lockfile
      shell: sh
      working-directory: ${{ inputs.working-directory }}
