name: firebase deploy

on:
  workflow_call:
    inputs:
      workload-identity-project-number:
        description: the GCP project number used for Workload Identity Federation
        required: true
        type: string
      environment:
        description: The firebase project environment used for the deployment
        required: true
        type: string
      gcp-service-account:
        description: the email address of the service account
        required: true
        type: string
      pre-deploy-command:
        description: the command to run before the firebase deploy
        required: false
        type: string
      working-directory:
        description: The working directory of the firebase project
        required: false
        type: string
        default: functions

concurrency:
  group: firebase-deploy-${{ inputs.environment }}

jobs:
  deploy:
    name: Firebase deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - uses: valian-ca/github-workflows/.github/actions/gcp-github-auth@main
        with:
          workload-identity-project-number: ${{ inputs.workload-identity-project-number }}
          service_account: ${{ inputs.gcp-service-account }}

      - name: Configure firebase environment
        run: npx firebase use ${{ inputs.environment }}
        working-directory: ${{ inputs.working-directory }}

      - name: Execute pre-deploy command
        if: inputs.pre-deploy-command != ''
        run: ${{ inputs.pre-deploy-command }}
        working-directory: ${{ inputs.working-directory }}

      - name: Firebase deploy
        run: npx firebase deploy --force
        working-directory: ${{ inputs.working-directory }}
